# Customize these as needed
title: SDG Translations
description: >-
  A project to compile and translate text related to the United Nation's
  Sustainable Development Goals, and then provide those translations as JSON.
baseurl: "/sdg-translations"
url: "https://opendataenterprise.github.io"
repo: "https://github.com/opendataenterprise/sdg-translations"

# Build settings
markdown: kramdown
source: www
theme: uswds-jekyll

# Python scripts build these files, so tell Jekyll not to process them
keep_files:
  - "*.json"
  - "*.csv"
